### ISSUE TITLE
Feature Request: Comments from Mastodon

### ISSUE THREAD

**Issue by kdmcguire** [chrismwilliams/astro-theme-cactus#107]
Hello! First off, I love this theme and am very grateful that you've shared it.

I've seen other people add Mastodon-powered comments to their blogs (any blogs, not necessarily Astro) and I think it's a great idea. I would try to do it myself, as I've already forked and customised the project a bit, but I am Terrible At Design and don't really know what I'm doing.

This person seems to have made it work: https://sam.pikesley.org/blog/2023/03/06/mastodon-powered-comments-in-astro/

From your comments on the search feature request, I understand that you might not want to include a *Mastodon*-specific comments component, but I'm curious to hear your thoughts either way.

Edit: this person has gone further and combined Mastodon comments and webmentions! https://kld.dev/adding-webmentions

**Comment by chrismwilliams** [comment]
Hi @kdmcguire, thanks, and appreciate the suggestion. Atm I'm holding off on adding stuff in except simple fixes due to astro about to hit v3.0 so I'm hoping nothing is going to break when updated. Once that's done, I will definitely circle back round and take a look at this.

**Comment by chrismwilliams** [comment]
Hi @kdmcguire, I've created a [working branch](https://github.com/chrismwilliams/astro-theme-cactus/tree/feature/webmentions) for integrating webmentions to the theme. 

I'm hoping to merge it with main soon but it's quite hard to test due to lack of actual webmentions the site has. If you, or anyone else reading this, get a chance to test this out and give some feedback it would really help. I've created a [blog post](https://feature-webmentions--astro-theme-cactus.netlify.app/posts/webmentions/) to accompany this which should hopefully help in setting it up.

**Comment by kdmcguire** [comment]
Ah, amazing! How can I help test it? If I posted on Mastodon with a link to that post, would it appear in the 'Webmentions for this post' list?

**Comment by kdmcguire** [comment]
This seems to work perfectly!

https://deploy-preview-198--kieran-mcguire.netlify.app/posts/monday-ritual/

**Comment by chrismwilliams** [comment]
Brilliant, thanks for letting me know.

Ah yeah apologies, that was me trying to be clever and thinking it would be easier to set everything in that file, `site.config.ts`. Unfortunately, astro doesn't like people doing that and blows up, I just forgot to change the comment back.
