### ISSUE TITLE
Cannot read properties of undefined (reading 'render')

### ISSUE THREAD

**Issue by tanveermunavar** [chrismwilliams/astro-theme-cactus#260]
Hi ,

Thanks for such a beautiful template, I'm loving it ! 

Im trying to enable web analytics for Vercel deployment of this template. 
https://vercel.com/docs/analytics/quickstart#add-the-analytics-component-to-your-app

I have appended below code in the configuration [here](https://github.com/chrismwilliams/astro-theme-cactus/blob/ff517620adccbc2ee43f2c72842ff8e3bdd7cced/astro.config.ts#L54) 

`  output: 'server',
  adapter: vercel({
    webAnalytics: {
      enabled: true,
    },
  }),`

Unfortunately I'm facing below issue. 

`
02:17:07 [WARN] [router] getStaticPaths() ignored in dynamic page /src/pages/posts/[slug].astro. Add `export const prerender = true;` to prerender the page as static HTML during the build process.
02:17:07 [WARN] [router] getStaticPaths() ignored in dynamic page /src/pages/posts/[...page].astro. Add `export const prerender = true;` to prerender the page as static HTML during the build process.
02:17:07 [ERROR] Cannot read properties of undefined (reading 'render')
  Stack trace:
    at /Users/mt/Documents/tmo/github/tmolabs.com/src/pages/posts/[slug].astro:18:33
    [...] See full stack trace in the browser, or rerun with --verbose.
02:17:07 [ERROR] Cannot read properties of undefined (reading 'render')
  Stack trace:
    at /Users/mt/Documents/tmo/github/tmolabs.com/src/pages/posts/[slug].astro:18:33
    [...] See full stack trace in the browser, or rerun with --verbose.
02:17:28 [ERROR] Cannot read properties of undefined (reading 'render')
  Stack trace:
    at /Users/mt/Documents/tmo/github/tmolabs.com/src/pages/posts/[slug].astro:18:33
    [...] See full stack trace in the browser, or rerun with --verbose.
02:17:28 [ERROR] Cannot read properties of undefined (reading 'render')
  Stack trace:
    at /Users/mt/Documents/tmo/github/tmolabs.com/src/pages/posts/[slug].astro:18:33
    [...] See full stack trace in the browser, or rerun with --verbose.
`

Any help would be appreciated. 

Thanks,
Tanveer Munavar

**Comment by chrismwilliams** [comment]
Hey @tanveermunavar,

Once you enable Astro's SSR mode, `getStaticPaths()` no longer works for generating routes [(as per docs)](https://docs.astro.build/en/guides/routing/#modifying-the-slug-example-for-ssr).

You have a couple of options though, depending on whether you require SSR. 
- If you do, and you want to SSR these pages, you're going to have to re-write every `getStaticPaths()` instance, as shown in the docs linked previous.
- Otherwise, as alluded to in the error, change the output to "hybrid" and add `const prerender = true;` to routes with `getStaticPaths()`
- Or just set the output to "static", as shown in the [adaptor docs](https://docs.astro.build/en/guides/integrations-guide/vercel/#choosing-a-target)

Hope that helps
