### ISSUE TITLE
In dark mode, there is a momentary white screen when switching pages

### ISSUE THREAD

**Issue by LamiaLoveless** [chrismwilliams/astro-theme-cactus#263]
This doesn't happen with cloudflare's default subdomains, but the custom domains do

**Comment by chrismwilliams** [comment]
I'm not quite sure what you mean by bundled domains, but my guess is that your the issue is with your build and or host. The js required for dark mode is intentionally setup in the theme to be render-blocking to prevent FOUC. My guess is that this is being modified in build/post-build. 

Just make sure your build is what you expect and may require manual checking, I do have an example of this theme on cloudflare [here](https://astro-theme-cactus.pages.dev/) to compare against.
