### ISSUE TITLE
Feature Request: support static search

### ISSUE THREAD

**Issue by Hasenpfote** [chrismwilliams/astro-theme-cactus#57]
I am just implementing a static search feature using "[page-find](https://pagefind.app)".
May I send a PR?

**Comment by chrismwilliams** [comment]
Hi @Hasenpfote thanks for this. At this moment in time I'm probably not going to add a search feature, mainly due to differing user needs/requirement and picking one single solution which some people may or may-not like or want and them having to do a bunch of work as soon as they use the template, a bit like analytics really.

What we can do though is leave this open and if it gets some traction/interest circle back and see what people want, and if enough people want a default search then I'll definitely be keen and ask for your help if that's okay.

**Comment by Hasenpfote** [comment]
I guess I did not understand the concept of the theme.
I generally agree with your opinion.

By the way, the planned feature was something like this.
[example](https://deploy-preview-15--adorable-nasturtium-4e1a8b.netlify.app)

**Comment by chrismwilliams** [comment]
@Hasenpfote that looks really, really good and nicely fits the theme. Yeah I know of a couple of users of algolia, and I don't fancy adding a generic 'shell' where users would plug in the back-end search functionality, if that makes sense. I'd rather pick a single solution and this is the best I've seen so far, and if more people ask then I'll add it in.

**Comment by chrismwilliams** [comment]
As an aside I know @gotofritz was looking for a mastodon icon #49, I don't know if you could share where you got it from please as the ones I use don't include it unfortunately.

**Comment by Hasenpfote** [comment]
@chrismwilliams
I used Algolia in Gatsby, so I know what you mean.
I like Pagefind only because it has no external dependencies and is simple.
But I'm not going to stick with it.

Also, this issue can be simplified.
It just needs to be a means of roughly identifying a post among many posts.
However, tags are not included here, as they will not work if forgotten or mistakenly added.

@gotofritz
I found the Mastodon icon [here](https://tabler-icons.io).
Please note that the license is different from https://tablericons.com.

**Comment by gotofritz** [comment]
Thanks for the link @Hasenpfote

As for search, funnily enougn I was going to add it to my own instance too, so ad definite +1 from me.
